config/routes.rb
OnlineClassroom::Application.routes.draw do

  get 'user/groups' => 'groups#index', as: :groups
  get 'user/groups/join/:id' => 'groups#join', :as => :join_group
  get 'user/groups/leave/:id' => 'groups#leave', :as => :leave_group
  put 'user/groups/update' => 'groups#update_user_associations', :as => :group_update

  devise_for :users

  root :to => 'home#index'
  get 'home/index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    # See the wiki for help on this file:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    guest=user.nil?

    # If user does not logged, create an guest user
    user||=User.new

    subject_group=[Subject, Answer, PossibleAnswer, Question]
    all_resources=subject_group + [Group]

    unless guest then

      cannot :manage, all_resources

      # Permissions for all users
      can [:join,:index, :leave,:update_user_associations], Group # All users can join a group
      can :view, Group do |g| # All users can view their group
        g.users.include? user
      end

      if user.has_role? :teacher
        can :create, all_resources # A teacher can create all resources on the website
        can :manage, subject_group, :teacher => user # Teacher can manage its own subjects
        can :manage, Group do |g| # Teacher can manage its groups
          g.teachers.include? user
        end
        cannot :destroy, Group do |g| # Teacher can not destroy its group
          g.teachers.count > 1 # if their is another teacher
        end
      else #Then the user is a student
        can :answer, Subject do |s|
          !(s.groups & user.groups).empty?
        end
      end
    end
    end
  end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :possible_answer_id, :user_id, :user, :question, :subject
  belongs_to :user
  belongs_to :possible_answer
  has_one :question, :through => :possible_answer
  has_one :subject, :through => :question
  has_one :teacher, :through => :subject
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :users, :subjects

  validates :name, :presence => true, :length => {minimum: 2}

  has_and_belongs_to_many :subjects

  has_and_belongs_to_many :users

  def teachers
    User.with_role(:teacher) & users
  end

  def students
    users - teachers
  end
end

app/models/possible_answer.rb
class PossibleAnswer < ActiveRecord::Base
  attr_accessible :answer, :correct, :question_id

  belongs_to :question
  has_one :subject, :through => :question
  has_one :teacher, :through => :subject

  has_many :answers

  validates :question, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :subject_id, :text, :subject, :possible_answers, :answers
  belongs_to :subject
  has_many :possible_answers
  has_many :answers, :through => :possible_answers
  has_one :teacher, :through => :subject

  validates_associated :subject
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :description, :teacher_id, :title, :questions, :answers

  belongs_to :teacher, :class_name => 'User'
  validates_associated :teacher

  has_many :questions
  has_many :answers, :through => :questions

  has_and_belongs_to_many :groups
  validates_associated :groups
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :group_ids, :groups
  # attr_accessible :title, :body

  has_and_belongs_to_many :groups

  has_many :answers

  def subjects
    subjects=[]
    groups.each do |g|
      subjects << g.subjects
    end
    subjects
  end

  def self.students
    User.all - User.with_role(:teacher)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  check_authorization :unless => :devise_controller?
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  skip_authorization_check :only => [:index,:update_user_associations]

  def new
  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @groups = Group.all
    respond_to do |format|
      format.json do
        render :json => @groups.to_json
      end
      format.html
    end
  end

  def update_user_associations
    unless params[:user] then return_bad_gateway end
    unless params[:user][:group_ids] then return_bad_gateway end
    current_user.group_ids = params[:user][:group_ids]
    unless current_user.save
      respond_to do |format|
        format.html do
          render :nothing => true, :status => :internal_server_error
        end
        format.json do
          render :json => {
              success: false,
              error: 500
          }, :status => :internal_server_error
        end
      end
    else
      flash[:notice] = t('groups.success.save')
      respond_to do |format|
        format.html do
          redirect_to groups_path
        end
        format.json do
          render :json => {
              success: true
          }
        end
      end
    end
  end

  def show
  end

  def join
    unless params[:id] then go_on_user_account_page end
    @user = current_user
    @group = Group.where(id: params[:id]).first!
    saved=false
    error=nil
    if @user.groups.include? @group then
      saved=false
      error = t('groups.errors.already_in_this_group')
    else
      @user.groups << @group
      saved = @user.save
      error = t('groups.errors.error_when_join', :name=>@group.name) unless saved
    end
    respond_to do |format|
      format.html do
        flash[:error]= error if error!=nil
        go_on_user_account_page
      end
      format.json do
        data={
            success: saved
        }
        data[:error] = error unless error == nil
        render :json => data
      end
    end
  end

  def leave
    unless params[:id] then go_on_user_account_page end
    @user = current_user
    @group = Group.where(id: params[:id]).first!
    saved=false
    error=nil
    if @user.groups.include? @group then
      @user.groups.delete @group
      saved=@user.save
      error = t('groups.errors.error_when_leave', :name=>@group.name) unless saved
    else
      saved = false
      error = t('groups.errors.not_in_this_group')
    end
    respond_to do |format|
      format.html do
        flash[:error]= error if error!=nil
        go_on_user_account_page
      end
      format.json do
        data={
            success: saved
        }
        data[:error] = error unless error == nil
        render :json => data
      end
    end
  end

  private

  def go_on_user_account_page
    redirect_to edit_registration_path(User)
  end

  def return_bad_gateway
    render :nothing => true, :status => :bad_gateway
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check

  def index
  end
end

app/controllers/users/registrations_controller.rb
 class Users::RegistrationsController < Devise::RegistrationsController
  def new
    puts 'Hello it is me'
     super
  end

  # def create
  #   super
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'current' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<h1><%= t('groups.title') %></h1>
<p><%= t('groups.head_text') %></p>
<% user=current_user %>
<%= simple_form_for user, :url => group_update_path, :html => {class:'form-horizontal'} do |f| %>
  <%= f.association :groups%>
  <div class="form-actions">
    <%= f.button :submit, t('actions.save'), :class => %w{btn btn-primary} %>
  </div>
<% end %>

app/views/groups/join.html.erb
<h1>Groups#join</h1>
<p>Find me in app/views/groups/join.html.erb</p>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>

app/views/home/index.html.erb
<h1><%=	I18n.translate 'home.home' %></h1>
<p><%=	I18n.translate 'home.welcome_message' %></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
<a class="brand" href="#">OnlineClassroom</a>
<div class="nav-collapse collapse">
  <ul class="nav">
    <%= nav_link t('locations.home'), root_path %>
  </ul>
  <ul class="nav pull-right">
    <li class="<%= if user_signed_in? then 'dropdown' else '' end%>">
      <% if user_signed_in? then%>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.email %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <%= nav_link t('devise.actions.my_account'), edit_user_registration_path %>
            <%= nav_link t('groups.title'), groups_path %>
            <li>
              <%=	link_to I18n.translate('devise.actions.logout'), destroy_user_session_path, :method => :delete %>
            </li>
          </ul>
      <% else %>
          <li><%=	link_to I18n.translate('devise.actions.login'), new_user_session_path %></li>
    <% end %>
    </li>
  </ul>
</div><!--/.nav-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineClassroom</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
          <%= render partial: 'layouts/navigation' %>
      </div>
    </div>
  </div>
<div class="container">
  <%= render partial: 'layouts/messages' %>

<%= yield %>

    </div>
</body>
</html>